A <%= @exception.class %> occurred in <%= @kontroller.controller_name %>#<%= @kontroller.action_name %>:

  <%= raw @exception.message %>
  <%= raw @backtrace.first %>

<%
  begin
    sections = @sections.map do |section|
      summary = render(section).strip
      unless summary.blank?
        title = render("title", :title => section).strip
        "#{title}\n\n#{summary.gsub(/^/, "  ")}\n\n"
      end
    end

  rescue Exception => e
    sections = ["(ERROR: Failed to generate exception summary: %s)" % e.message]
  end
%>

<%= raw sections.join %>
